version: '3.8'

services:
  web:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npm install && npm run start"